set_pns_commit_mode true
# Starting to commit core rings
create_power_straps  -direction horizontal  -start_at 2.7000 -nets VDD -layer 23 -width 3.8000 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.1900 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction horizontal  -start_at 101.1000 -nets VDD -layer 23 -width 3.8000 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.1900 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction vertical  -start_at 101.2900 -nets VDD -layer 25 -width 3.8000 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.0000 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction vertical  -start_at 2.7000 -nets VDD -layer 25 -width 3.8000 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.0000 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction horizontal  -start_at 2.7000 -nets VDD -layer 27 -width 3.8000 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.1900 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction horizontal  -start_at 101.1000 -nets VDD -layer 27 -width 3.8000 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.1900 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction vertical  -start_at 101.2900 -nets VDD -layer 29 -width 3.8000 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.0000 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction vertical  -start_at 2.7000 -nets VDD -layer 29 -width 3.8000 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.0000 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction horizontal  -start_at 7.3000 -nets VSS -layer 23 -width 3.8000 -start_low_ends coordinate  -start_low_ends_coordinate 5.4000 -start_high_ends coordinate  -start_high_ends_coordinate 98.5900 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction horizontal  -start_at 96.5000 -nets VSS -layer 23 -width 3.8000 -start_low_ends coordinate  -start_low_ends_coordinate 5.4000 -start_high_ends coordinate  -start_high_ends_coordinate 98.5900 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction vertical  -start_at 96.6900 -nets VSS -layer 25 -width 3.8000 -start_low_ends coordinate  -start_low_ends_coordinate 5.4000 -start_high_ends coordinate  -start_high_ends_coordinate 98.4000 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction vertical  -start_at 7.3000 -nets VSS -layer 25 -width 3.8000 -start_low_ends coordinate  -start_low_ends_coordinate 5.4000 -start_high_ends coordinate  -start_high_ends_coordinate 98.4000 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction horizontal  -start_at 7.3000 -nets VSS -layer 27 -width 3.8000 -start_low_ends coordinate  -start_low_ends_coordinate 5.4000 -start_high_ends coordinate  -start_high_ends_coordinate 98.5900 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction horizontal  -start_at 96.5000 -nets VSS -layer 27 -width 3.8000 -start_low_ends coordinate  -start_low_ends_coordinate 5.4000 -start_high_ends coordinate  -start_high_ends_coordinate 98.5900 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction vertical  -start_at 96.6900 -nets VSS -layer 29 -width 3.8000 -start_low_ends coordinate  -start_low_ends_coordinate 5.4000 -start_high_ends coordinate  -start_high_ends_coordinate 98.4000 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction vertical  -start_at 7.3000 -nets VSS -layer 29 -width 3.8000 -start_low_ends coordinate  -start_low_ends_coordinate 5.4000 -start_high_ends coordinate  -start_high_ends_coordinate 98.4000 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
# Starting to commit block rings
# Starting to commit metal6 straps for net VDD
create_power_straps  -direction vertical  -start_at 13.6950 -nets VDD  -layer 21 -width 0.1400 -pitch_within_group 3.9700 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.0000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 18.2550 -nets VDD  -layer 21 -width 0.1400 -pitch_within_group 3.9700 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.0000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 22.0550 -nets VDD  -layer 21 -width 0.1400 -pitch_within_group 3.9700 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.0000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 25.8550 -nets VDD  -layer 21 -width 0.1400 -pitch_within_group 3.9700 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.0000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 29.6550 -nets VDD  -layer 21 -width 0.1400 -pitch_within_group 3.9700 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.0000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 34.2150 -nets VDD  -layer 21 -width 0.1400 -pitch_within_group 3.9700 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.0000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 38.0150 -nets VDD  -layer 21 -width 0.1400 -pitch_within_group 3.9700 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.0000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 41.8150 -nets VDD  -layer 21 -width 0.1400 -pitch_within_group 3.9700 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.0000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 45.6150 -nets VDD  -layer 21 -width 0.1400 -pitch_within_group 3.9700 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.0000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 49.4150 -nets VDD  -layer 21 -width 0.1400 -pitch_within_group 3.9700 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.0000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 53.9750 -nets VDD  -layer 21 -width 0.1400 -pitch_within_group 3.9700 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.0000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 57.7750 -nets VDD  -layer 21 -width 0.1400 -pitch_within_group 3.9700 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.0000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 61.5750 -nets VDD  -layer 21 -width 0.1400 -pitch_within_group 3.9700 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.0000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 65.3750 -nets VDD  -layer 21 -width 0.1400 -pitch_within_group 3.9700 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.0000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 69.9350 -nets VDD  -layer 21 -width 0.1400 -pitch_within_group 3.9700 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.0000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 73.7350 -nets VDD  -layer 21 -width 0.1400 -pitch_within_group 3.9700 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.0000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 77.5350 -nets VDD  -layer 21 -width 0.1400 -pitch_within_group 3.9700 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.0000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 81.3350 -nets VDD  -layer 21 -width 0.1400 -pitch_within_group 3.9700 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.0000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 85.8950 -nets VDD  -layer 21 -width 0.1400 -pitch_within_group 3.9700 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.0000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 89.6950 -nets VDD  -layer 21 -width 0.1400 -pitch_within_group 3.9700 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.0000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
# Starting to commit metal6 straps for net VSS
create_power_straps  -direction vertical  -start_at 14.1050 -nets VSS  -layer 21 -width 0.1400 -pitch_within_group 3.9700 -start_low_ends coordinate  -start_low_ends_coordinate 5.4000 -start_high_ends coordinate  -start_high_ends_coordinate 98.4000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 18.6650 -nets VSS  -layer 21 -width 0.1400 -pitch_within_group 3.9700 -start_low_ends coordinate  -start_low_ends_coordinate 5.4000 -start_high_ends coordinate  -start_high_ends_coordinate 98.4000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 22.4650 -nets VSS  -layer 21 -width 0.1400 -pitch_within_group 3.9700 -start_low_ends coordinate  -start_low_ends_coordinate 5.4000 -start_high_ends coordinate  -start_high_ends_coordinate 98.4000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 26.2650 -nets VSS  -layer 21 -width 0.1400 -pitch_within_group 3.9700 -start_low_ends coordinate  -start_low_ends_coordinate 5.4000 -start_high_ends coordinate  -start_high_ends_coordinate 98.4000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 30.0650 -nets VSS  -layer 21 -width 0.1400 -pitch_within_group 3.9700 -start_low_ends coordinate  -start_low_ends_coordinate 5.4000 -start_high_ends coordinate  -start_high_ends_coordinate 98.4000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 34.6250 -nets VSS  -layer 21 -width 0.1400 -pitch_within_group 3.9700 -start_low_ends coordinate  -start_low_ends_coordinate 5.4000 -start_high_ends coordinate  -start_high_ends_coordinate 98.4000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 38.4250 -nets VSS  -layer 21 -width 0.1400 -pitch_within_group 3.9700 -start_low_ends coordinate  -start_low_ends_coordinate 5.4000 -start_high_ends coordinate  -start_high_ends_coordinate 98.4000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 42.2250 -nets VSS  -layer 21 -width 0.1400 -pitch_within_group 3.9700 -start_low_ends coordinate  -start_low_ends_coordinate 5.4000 -start_high_ends coordinate  -start_high_ends_coordinate 98.4000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 46.0250 -nets VSS  -layer 21 -width 0.1400 -pitch_within_group 3.9700 -start_low_ends coordinate  -start_low_ends_coordinate 5.4000 -start_high_ends coordinate  -start_high_ends_coordinate 98.4000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 49.8250 -nets VSS  -layer 21 -width 0.1400 -pitch_within_group 3.9700 -start_low_ends coordinate  -start_low_ends_coordinate 5.4000 -start_high_ends coordinate  -start_high_ends_coordinate 98.4000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 54.3850 -nets VSS  -layer 21 -width 0.1400 -pitch_within_group 3.9700 -start_low_ends coordinate  -start_low_ends_coordinate 5.4000 -start_high_ends coordinate  -start_high_ends_coordinate 98.4000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 58.1850 -nets VSS  -layer 21 -width 0.1400 -pitch_within_group 3.9700 -start_low_ends coordinate  -start_low_ends_coordinate 5.4000 -start_high_ends coordinate  -start_high_ends_coordinate 98.4000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 61.9850 -nets VSS  -layer 21 -width 0.1400 -pitch_within_group 3.9700 -start_low_ends coordinate  -start_low_ends_coordinate 5.4000 -start_high_ends coordinate  -start_high_ends_coordinate 98.4000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 65.7850 -nets VSS  -layer 21 -width 0.1400 -pitch_within_group 3.9700 -start_low_ends coordinate  -start_low_ends_coordinate 5.4000 -start_high_ends coordinate  -start_high_ends_coordinate 98.4000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 70.3450 -nets VSS  -layer 21 -width 0.1400 -pitch_within_group 3.9700 -start_low_ends coordinate  -start_low_ends_coordinate 5.4000 -start_high_ends coordinate  -start_high_ends_coordinate 98.4000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 74.1450 -nets VSS  -layer 21 -width 0.1400 -pitch_within_group 3.9700 -start_low_ends coordinate  -start_low_ends_coordinate 5.4000 -start_high_ends coordinate  -start_high_ends_coordinate 98.4000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 77.9450 -nets VSS  -layer 21 -width 0.1400 -pitch_within_group 3.9700 -start_low_ends coordinate  -start_low_ends_coordinate 5.4000 -start_high_ends coordinate  -start_high_ends_coordinate 98.4000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 81.7450 -nets VSS  -layer 21 -width 0.1400 -pitch_within_group 3.9700 -start_low_ends coordinate  -start_low_ends_coordinate 5.4000 -start_high_ends coordinate  -start_high_ends_coordinate 98.4000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 86.3050 -nets VSS  -layer 21 -width 0.1400 -pitch_within_group 3.9700 -start_low_ends coordinate  -start_low_ends_coordinate 5.4000 -start_high_ends coordinate  -start_high_ends_coordinate 98.4000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 90.1050 -nets VSS  -layer 21 -width 0.1400 -pitch_within_group 3.9700 -start_low_ends coordinate  -start_low_ends_coordinate 5.4000 -start_high_ends coordinate  -start_high_ends_coordinate 98.4000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
# Starting to commit metal7 straps for net VDD
create_power_straps  -direction horizontal  -start_at 13.0550 -nets VDD  -layer 23 -width 0.4000 -pitch_within_group 3.9610 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.1900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 17.6150 -nets VDD  -layer 23 -width 0.4000 -pitch_within_group 3.9610 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.1900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 22.1750 -nets VDD  -layer 23 -width 0.4000 -pitch_within_group 3.9610 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.1900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 25.2150 -nets VDD  -layer 23 -width 0.4000 -pitch_within_group 3.9610 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.1900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 29.7750 -nets VDD  -layer 23 -width 0.4000 -pitch_within_group 3.9610 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.1900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 34.3350 -nets VDD  -layer 23 -width 0.4000 -pitch_within_group 3.9610 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.1900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 37.3750 -nets VDD  -layer 23 -width 0.4000 -pitch_within_group 3.9610 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.1900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 41.9350 -nets VDD  -layer 23 -width 0.4000 -pitch_within_group 3.9610 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.1900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 44.9750 -nets VDD  -layer 23 -width 0.4000 -pitch_within_group 3.9610 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.1900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 49.5350 -nets VDD  -layer 23 -width 0.4000 -pitch_within_group 3.9610 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.1900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 54.0950 -nets VDD  -layer 23 -width 0.4000 -pitch_within_group 3.9610 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.1900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 57.1350 -nets VDD  -layer 23 -width 0.4000 -pitch_within_group 3.9610 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.1900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 61.6950 -nets VDD  -layer 23 -width 0.4000 -pitch_within_group 3.9610 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.1900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 64.7350 -nets VDD  -layer 23 -width 0.4000 -pitch_within_group 3.9610 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.1900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 69.2950 -nets VDD  -layer 23 -width 0.4000 -pitch_within_group 3.9610 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.1900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 73.8550 -nets VDD  -layer 23 -width 0.4000 -pitch_within_group 3.9610 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.1900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 76.8950 -nets VDD  -layer 23 -width 0.4000 -pitch_within_group 3.9610 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.1900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 81.4550 -nets VDD  -layer 23 -width 0.4000 -pitch_within_group 3.9610 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.1900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 84.4950 -nets VDD  -layer 23 -width 0.4000 -pitch_within_group 3.9610 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.1900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 89.0550 -nets VDD  -layer 23 -width 0.4000 -pitch_within_group 3.9610 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.1900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
# Starting to commit metal7 straps for net VSS
create_power_straps  -direction horizontal  -start_at 13.9850 -nets VSS  -layer 23 -width 0.4000 -pitch_within_group 3.9610 -start_low_ends coordinate  -start_low_ends_coordinate 5.4000 -start_high_ends coordinate  -start_high_ends_coordinate 98.5900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 18.5450 -nets VSS  -layer 23 -width 0.4000 -pitch_within_group 3.9610 -start_low_ends coordinate  -start_low_ends_coordinate 5.4000 -start_high_ends coordinate  -start_high_ends_coordinate 98.5900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 23.1050 -nets VSS  -layer 23 -width 0.4000 -pitch_within_group 3.9610 -start_low_ends coordinate  -start_low_ends_coordinate 5.4000 -start_high_ends coordinate  -start_high_ends_coordinate 98.5900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 26.1450 -nets VSS  -layer 23 -width 0.4000 -pitch_within_group 3.9610 -start_low_ends coordinate  -start_low_ends_coordinate 5.4000 -start_high_ends coordinate  -start_high_ends_coordinate 98.5900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 30.7050 -nets VSS  -layer 23 -width 0.4000 -pitch_within_group 3.9610 -start_low_ends coordinate  -start_low_ends_coordinate 5.4000 -start_high_ends coordinate  -start_high_ends_coordinate 98.5900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 35.2650 -nets VSS  -layer 23 -width 0.4000 -pitch_within_group 3.9610 -start_low_ends coordinate  -start_low_ends_coordinate 5.4000 -start_high_ends coordinate  -start_high_ends_coordinate 98.5900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 38.3050 -nets VSS  -layer 23 -width 0.4000 -pitch_within_group 3.9610 -start_low_ends coordinate  -start_low_ends_coordinate 5.4000 -start_high_ends coordinate  -start_high_ends_coordinate 98.5900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 42.8650 -nets VSS  -layer 23 -width 0.4000 -pitch_within_group 3.9610 -start_low_ends coordinate  -start_low_ends_coordinate 5.4000 -start_high_ends coordinate  -start_high_ends_coordinate 98.5900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 45.9050 -nets VSS  -layer 23 -width 0.4000 -pitch_within_group 3.9610 -start_low_ends coordinate  -start_low_ends_coordinate 5.4000 -start_high_ends coordinate  -start_high_ends_coordinate 98.5900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 50.4650 -nets VSS  -layer 23 -width 0.4000 -pitch_within_group 3.9610 -start_low_ends coordinate  -start_low_ends_coordinate 5.4000 -start_high_ends coordinate  -start_high_ends_coordinate 98.5900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 55.0250 -nets VSS  -layer 23 -width 0.4000 -pitch_within_group 3.9610 -start_low_ends coordinate  -start_low_ends_coordinate 5.4000 -start_high_ends coordinate  -start_high_ends_coordinate 98.5900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 58.0650 -nets VSS  -layer 23 -width 0.4000 -pitch_within_group 3.9610 -start_low_ends coordinate  -start_low_ends_coordinate 5.4000 -start_high_ends coordinate  -start_high_ends_coordinate 98.5900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 62.6250 -nets VSS  -layer 23 -width 0.4000 -pitch_within_group 3.9610 -start_low_ends coordinate  -start_low_ends_coordinate 5.4000 -start_high_ends coordinate  -start_high_ends_coordinate 98.5900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 65.6650 -nets VSS  -layer 23 -width 0.4000 -pitch_within_group 3.9610 -start_low_ends coordinate  -start_low_ends_coordinate 5.4000 -start_high_ends coordinate  -start_high_ends_coordinate 98.5900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 70.2250 -nets VSS  -layer 23 -width 0.4000 -pitch_within_group 3.9610 -start_low_ends coordinate  -start_low_ends_coordinate 5.4000 -start_high_ends coordinate  -start_high_ends_coordinate 98.5900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 74.7850 -nets VSS  -layer 23 -width 0.4000 -pitch_within_group 3.9610 -start_low_ends coordinate  -start_low_ends_coordinate 5.4000 -start_high_ends coordinate  -start_high_ends_coordinate 98.5900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 77.8250 -nets VSS  -layer 23 -width 0.4000 -pitch_within_group 3.9610 -start_low_ends coordinate  -start_low_ends_coordinate 5.4000 -start_high_ends coordinate  -start_high_ends_coordinate 98.5900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 82.3850 -nets VSS  -layer 23 -width 0.4000 -pitch_within_group 3.9610 -start_low_ends coordinate  -start_low_ends_coordinate 5.4000 -start_high_ends coordinate  -start_high_ends_coordinate 98.5900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 85.4250 -nets VSS  -layer 23 -width 0.4000 -pitch_within_group 3.9610 -start_low_ends coordinate  -start_low_ends_coordinate 5.4000 -start_high_ends coordinate  -start_high_ends_coordinate 98.5900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 89.9850 -nets VSS  -layer 23 -width 0.4000 -pitch_within_group 3.9610 -start_low_ends coordinate  -start_low_ends_coordinate 5.4000 -start_high_ends coordinate  -start_high_ends_coordinate 98.5900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
# Starting to commit metal8 straps for net VDD
create_power_straps  -direction vertical  -start_at 13.8800 -nets VDD  -layer 25 -width 0.4000 -pitch_within_group 3.9700 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.0000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 18.4400 -nets VDD  -layer 25 -width 0.4000 -pitch_within_group 3.9700 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.0000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 21.4800 -nets VDD  -layer 25 -width 0.4000 -pitch_within_group 3.9700 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.0000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 26.0400 -nets VDD  -layer 25 -width 0.4000 -pitch_within_group 3.9700 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.0000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 29.0800 -nets VDD  -layer 25 -width 0.4000 -pitch_within_group 3.9700 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.0000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 33.6400 -nets VDD  -layer 25 -width 0.4000 -pitch_within_group 3.9700 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.0000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 38.2000 -nets VDD  -layer 25 -width 0.4000 -pitch_within_group 3.9700 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.0000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 41.2400 -nets VDD  -layer 25 -width 0.4000 -pitch_within_group 3.9700 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.0000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 45.8000 -nets VDD  -layer 25 -width 0.4000 -pitch_within_group 3.9700 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.0000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 48.8400 -nets VDD  -layer 25 -width 0.4000 -pitch_within_group 3.9700 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.0000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 53.4000 -nets VDD  -layer 25 -width 0.4000 -pitch_within_group 3.9700 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.0000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 57.9600 -nets VDD  -layer 25 -width 0.4000 -pitch_within_group 3.9700 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.0000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 61.0000 -nets VDD  -layer 25 -width 0.4000 -pitch_within_group 3.9700 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.0000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 65.5600 -nets VDD  -layer 25 -width 0.4000 -pitch_within_group 3.9700 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.0000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 70.1200 -nets VDD  -layer 25 -width 0.4000 -pitch_within_group 3.9700 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.0000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 73.1600 -nets VDD  -layer 25 -width 0.4000 -pitch_within_group 3.9700 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.0000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 77.7200 -nets VDD  -layer 25 -width 0.4000 -pitch_within_group 3.9700 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.0000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 80.7600 -nets VDD  -layer 25 -width 0.4000 -pitch_within_group 3.9700 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.0000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 85.3200 -nets VDD  -layer 25 -width 0.4000 -pitch_within_group 3.9700 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.0000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 89.8800 -nets VDD  -layer 25 -width 0.4000 -pitch_within_group 3.9700 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.0000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
# Starting to commit metal8 straps for net VSS
create_power_straps  -direction vertical  -start_at 14.6800 -nets VSS  -layer 25 -width 0.4000 -pitch_within_group 3.9700 -start_low_ends coordinate  -start_low_ends_coordinate 5.4000 -start_high_ends coordinate  -start_high_ends_coordinate 98.4000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 19.2400 -nets VSS  -layer 25 -width 0.4000 -pitch_within_group 3.9700 -start_low_ends coordinate  -start_low_ends_coordinate 5.4000 -start_high_ends coordinate  -start_high_ends_coordinate 98.4000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 22.2800 -nets VSS  -layer 25 -width 0.4000 -pitch_within_group 3.9700 -start_low_ends coordinate  -start_low_ends_coordinate 5.4000 -start_high_ends coordinate  -start_high_ends_coordinate 98.4000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 26.8400 -nets VSS  -layer 25 -width 0.4000 -pitch_within_group 3.9700 -start_low_ends coordinate  -start_low_ends_coordinate 5.4000 -start_high_ends coordinate  -start_high_ends_coordinate 98.4000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 29.8800 -nets VSS  -layer 25 -width 0.4000 -pitch_within_group 3.9700 -start_low_ends coordinate  -start_low_ends_coordinate 5.4000 -start_high_ends coordinate  -start_high_ends_coordinate 98.4000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 34.4400 -nets VSS  -layer 25 -width 0.4000 -pitch_within_group 3.9700 -start_low_ends coordinate  -start_low_ends_coordinate 5.4000 -start_high_ends coordinate  -start_high_ends_coordinate 98.4000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 39.0000 -nets VSS  -layer 25 -width 0.4000 -pitch_within_group 3.9700 -start_low_ends coordinate  -start_low_ends_coordinate 5.4000 -start_high_ends coordinate  -start_high_ends_coordinate 98.4000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 42.0400 -nets VSS  -layer 25 -width 0.4000 -pitch_within_group 3.9700 -start_low_ends coordinate  -start_low_ends_coordinate 5.4000 -start_high_ends coordinate  -start_high_ends_coordinate 98.4000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 46.6000 -nets VSS  -layer 25 -width 0.4000 -pitch_within_group 3.9700 -start_low_ends coordinate  -start_low_ends_coordinate 5.4000 -start_high_ends coordinate  -start_high_ends_coordinate 98.4000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 49.6400 -nets VSS  -layer 25 -width 0.4000 -pitch_within_group 3.9700 -start_low_ends coordinate  -start_low_ends_coordinate 5.4000 -start_high_ends coordinate  -start_high_ends_coordinate 98.4000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 54.2000 -nets VSS  -layer 25 -width 0.4000 -pitch_within_group 3.9700 -start_low_ends coordinate  -start_low_ends_coordinate 5.4000 -start_high_ends coordinate  -start_high_ends_coordinate 98.4000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 58.7600 -nets VSS  -layer 25 -width 0.4000 -pitch_within_group 3.9700 -start_low_ends coordinate  -start_low_ends_coordinate 5.4000 -start_high_ends coordinate  -start_high_ends_coordinate 98.4000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 61.8000 -nets VSS  -layer 25 -width 0.4000 -pitch_within_group 3.9700 -start_low_ends coordinate  -start_low_ends_coordinate 5.4000 -start_high_ends coordinate  -start_high_ends_coordinate 98.4000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 66.3600 -nets VSS  -layer 25 -width 0.4000 -pitch_within_group 3.9700 -start_low_ends coordinate  -start_low_ends_coordinate 5.4000 -start_high_ends coordinate  -start_high_ends_coordinate 98.4000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 70.9200 -nets VSS  -layer 25 -width 0.4000 -pitch_within_group 3.9700 -start_low_ends coordinate  -start_low_ends_coordinate 5.4000 -start_high_ends coordinate  -start_high_ends_coordinate 98.4000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 73.9600 -nets VSS  -layer 25 -width 0.4000 -pitch_within_group 3.9700 -start_low_ends coordinate  -start_low_ends_coordinate 5.4000 -start_high_ends coordinate  -start_high_ends_coordinate 98.4000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 78.5200 -nets VSS  -layer 25 -width 0.4000 -pitch_within_group 3.9700 -start_low_ends coordinate  -start_low_ends_coordinate 5.4000 -start_high_ends coordinate  -start_high_ends_coordinate 98.4000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 81.5600 -nets VSS  -layer 25 -width 0.4000 -pitch_within_group 3.9700 -start_low_ends coordinate  -start_low_ends_coordinate 5.4000 -start_high_ends coordinate  -start_high_ends_coordinate 98.4000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 86.1200 -nets VSS  -layer 25 -width 0.4000 -pitch_within_group 3.9700 -start_low_ends coordinate  -start_low_ends_coordinate 5.4000 -start_high_ends coordinate  -start_high_ends_coordinate 98.4000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 90.6800 -nets VSS  -layer 25 -width 0.4000 -pitch_within_group 3.9700 -start_low_ends coordinate  -start_low_ends_coordinate 5.4000 -start_high_ends coordinate  -start_high_ends_coordinate 98.4000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
# Starting to commit metal9 straps for net VDD
create_power_straps  -direction horizontal  -start_at 14.2400 -nets VDD  -layer 27 -width 0.8000 -pitch_within_group 3.9610 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.1900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 17.2800 -nets VDD  -layer 27 -width 0.8000 -pitch_within_group 3.9610 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.1900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 20.3200 -nets VDD  -layer 27 -width 0.8000 -pitch_within_group 3.9610 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.1900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 26.4000 -nets VDD  -layer 27 -width 0.8000 -pitch_within_group 3.9610 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.1900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 29.4400 -nets VDD  -layer 27 -width 0.8000 -pitch_within_group 3.9610 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.1900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 32.4800 -nets VDD  -layer 27 -width 0.8000 -pitch_within_group 3.9610 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.1900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 38.5600 -nets VDD  -layer 27 -width 0.8000 -pitch_within_group 3.9610 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.1900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 41.6000 -nets VDD  -layer 27 -width 0.8000 -pitch_within_group 3.9610 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.1900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 44.6400 -nets VDD  -layer 27 -width 0.8000 -pitch_within_group 3.9610 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.1900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 47.6800 -nets VDD  -layer 27 -width 0.8000 -pitch_within_group 3.9610 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.1900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 53.7600 -nets VDD  -layer 27 -width 0.8000 -pitch_within_group 3.9610 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.1900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 56.8000 -nets VDD  -layer 27 -width 0.8000 -pitch_within_group 3.9610 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.1900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 59.8400 -nets VDD  -layer 27 -width 0.8000 -pitch_within_group 3.9610 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.1900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 65.9200 -nets VDD  -layer 27 -width 0.8000 -pitch_within_group 3.9610 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.1900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 68.9600 -nets VDD  -layer 27 -width 0.8000 -pitch_within_group 3.9610 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.1900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 72.0000 -nets VDD  -layer 27 -width 0.8000 -pitch_within_group 3.9610 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.1900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 78.0800 -nets VDD  -layer 27 -width 0.8000 -pitch_within_group 3.9610 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.1900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 81.1200 -nets VDD  -layer 27 -width 0.8000 -pitch_within_group 3.9610 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.1900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 84.1600 -nets VDD  -layer 27 -width 0.8000 -pitch_within_group 3.9610 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.1900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 87.2000 -nets VDD  -layer 27 -width 0.8000 -pitch_within_group 3.9610 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.1900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
# Starting to commit metal9 straps for net VSS
create_power_straps  -direction horizontal  -start_at 15.8400 -nets VSS  -layer 27 -width 0.8000 -pitch_within_group 3.9610 -start_low_ends coordinate  -start_low_ends_coordinate 5.4000 -start_high_ends coordinate  -start_high_ends_coordinate 98.5900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 18.8800 -nets VSS  -layer 27 -width 0.8000 -pitch_within_group 3.9610 -start_low_ends coordinate  -start_low_ends_coordinate 5.4000 -start_high_ends coordinate  -start_high_ends_coordinate 98.5900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 21.9200 -nets VSS  -layer 27 -width 0.8000 -pitch_within_group 3.9610 -start_low_ends coordinate  -start_low_ends_coordinate 5.4000 -start_high_ends coordinate  -start_high_ends_coordinate 98.5900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 28.0000 -nets VSS  -layer 27 -width 0.8000 -pitch_within_group 3.9610 -start_low_ends coordinate  -start_low_ends_coordinate 5.4000 -start_high_ends coordinate  -start_high_ends_coordinate 98.5900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 31.0400 -nets VSS  -layer 27 -width 0.8000 -pitch_within_group 3.9610 -start_low_ends coordinate  -start_low_ends_coordinate 5.4000 -start_high_ends coordinate  -start_high_ends_coordinate 98.5900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 34.0800 -nets VSS  -layer 27 -width 0.8000 -pitch_within_group 3.9610 -start_low_ends coordinate  -start_low_ends_coordinate 5.4000 -start_high_ends coordinate  -start_high_ends_coordinate 98.5900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 40.1600 -nets VSS  -layer 27 -width 0.8000 -pitch_within_group 3.9610 -start_low_ends coordinate  -start_low_ends_coordinate 5.4000 -start_high_ends coordinate  -start_high_ends_coordinate 98.5900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 43.2000 -nets VSS  -layer 27 -width 0.8000 -pitch_within_group 3.9610 -start_low_ends coordinate  -start_low_ends_coordinate 5.4000 -start_high_ends coordinate  -start_high_ends_coordinate 98.5900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 46.2400 -nets VSS  -layer 27 -width 0.8000 -pitch_within_group 3.9610 -start_low_ends coordinate  -start_low_ends_coordinate 5.4000 -start_high_ends coordinate  -start_high_ends_coordinate 98.5900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 49.2800 -nets VSS  -layer 27 -width 0.8000 -pitch_within_group 3.9610 -start_low_ends coordinate  -start_low_ends_coordinate 5.4000 -start_high_ends coordinate  -start_high_ends_coordinate 98.5900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 55.3600 -nets VSS  -layer 27 -width 0.8000 -pitch_within_group 3.9610 -start_low_ends coordinate  -start_low_ends_coordinate 5.4000 -start_high_ends coordinate  -start_high_ends_coordinate 98.5900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 58.4000 -nets VSS  -layer 27 -width 0.8000 -pitch_within_group 3.9610 -start_low_ends coordinate  -start_low_ends_coordinate 5.4000 -start_high_ends coordinate  -start_high_ends_coordinate 98.5900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 61.4400 -nets VSS  -layer 27 -width 0.8000 -pitch_within_group 3.9610 -start_low_ends coordinate  -start_low_ends_coordinate 5.4000 -start_high_ends coordinate  -start_high_ends_coordinate 98.5900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 67.5200 -nets VSS  -layer 27 -width 0.8000 -pitch_within_group 3.9610 -start_low_ends coordinate  -start_low_ends_coordinate 5.4000 -start_high_ends coordinate  -start_high_ends_coordinate 98.5900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 70.5600 -nets VSS  -layer 27 -width 0.8000 -pitch_within_group 3.9610 -start_low_ends coordinate  -start_low_ends_coordinate 5.4000 -start_high_ends coordinate  -start_high_ends_coordinate 98.5900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 73.6000 -nets VSS  -layer 27 -width 0.8000 -pitch_within_group 3.9610 -start_low_ends coordinate  -start_low_ends_coordinate 5.4000 -start_high_ends coordinate  -start_high_ends_coordinate 98.5900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 79.6800 -nets VSS  -layer 27 -width 0.8000 -pitch_within_group 3.9610 -start_low_ends coordinate  -start_low_ends_coordinate 5.4000 -start_high_ends coordinate  -start_high_ends_coordinate 98.5900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 82.7200 -nets VSS  -layer 27 -width 0.8000 -pitch_within_group 3.9610 -start_low_ends coordinate  -start_low_ends_coordinate 5.4000 -start_high_ends coordinate  -start_high_ends_coordinate 98.5900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 85.7600 -nets VSS  -layer 27 -width 0.8000 -pitch_within_group 3.9610 -start_low_ends coordinate  -start_low_ends_coordinate 5.4000 -start_high_ends coordinate  -start_high_ends_coordinate 98.5900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 88.8000 -nets VSS  -layer 27 -width 0.8000 -pitch_within_group 3.9610 -start_low_ends coordinate  -start_low_ends_coordinate 5.4000 -start_high_ends coordinate  -start_high_ends_coordinate 98.5900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
# Starting to commit metal10 straps for net VDD
create_power_straps  -direction vertical  -start_at 12.7200 -nets VDD  -layer 29 -width 0.8000 -pitch_within_group 3.9700 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.0000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 18.8000 -nets VDD  -layer 29 -width 0.8000 -pitch_within_group 3.9700 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.0000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 21.8400 -nets VDD  -layer 29 -width 0.8000 -pitch_within_group 3.9700 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.0000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 24.8800 -nets VDD  -layer 29 -width 0.8000 -pitch_within_group 3.9700 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.0000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 27.9200 -nets VDD  -layer 29 -width 0.8000 -pitch_within_group 3.9700 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.0000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 34.0000 -nets VDD  -layer 29 -width 0.8000 -pitch_within_group 3.9700 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.0000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 37.0400 -nets VDD  -layer 29 -width 0.8000 -pitch_within_group 3.9700 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.0000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 40.0800 -nets VDD  -layer 29 -width 0.8000 -pitch_within_group 3.9700 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.0000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 46.1600 -nets VDD  -layer 29 -width 0.8000 -pitch_within_group 3.9700 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.0000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 49.2000 -nets VDD  -layer 29 -width 0.8000 -pitch_within_group 3.9700 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.0000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 52.2400 -nets VDD  -layer 29 -width 0.8000 -pitch_within_group 3.9700 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.0000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 58.3200 -nets VDD  -layer 29 -width 0.8000 -pitch_within_group 3.9700 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.0000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 61.3600 -nets VDD  -layer 29 -width 0.8000 -pitch_within_group 3.9700 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.0000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 64.4000 -nets VDD  -layer 29 -width 0.8000 -pitch_within_group 3.9700 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.0000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 70.4800 -nets VDD  -layer 29 -width 0.8000 -pitch_within_group 3.9700 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.0000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 73.5200 -nets VDD  -layer 29 -width 0.8000 -pitch_within_group 3.9700 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.0000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 76.5600 -nets VDD  -layer 29 -width 0.8000 -pitch_within_group 3.9700 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.0000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 79.6000 -nets VDD  -layer 29 -width 0.8000 -pitch_within_group 3.9700 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.0000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 85.6800 -nets VDD  -layer 29 -width 0.8000 -pitch_within_group 3.9700 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.0000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 88.7200 -nets VDD  -layer 29 -width 0.8000 -pitch_within_group 3.9700 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.0000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
# Starting to commit metal10 straps for net VSS
create_power_straps  -direction vertical  -start_at 14.3200 -nets VSS  -layer 29 -width 0.8000 -pitch_within_group 3.9700 -start_low_ends coordinate  -start_low_ends_coordinate 5.4000 -start_high_ends coordinate  -start_high_ends_coordinate 98.4000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 20.4000 -nets VSS  -layer 29 -width 0.8000 -pitch_within_group 3.9700 -start_low_ends coordinate  -start_low_ends_coordinate 5.4000 -start_high_ends coordinate  -start_high_ends_coordinate 98.4000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 23.4400 -nets VSS  -layer 29 -width 0.8000 -pitch_within_group 3.9700 -start_low_ends coordinate  -start_low_ends_coordinate 5.4000 -start_high_ends coordinate  -start_high_ends_coordinate 98.4000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 26.4800 -nets VSS  -layer 29 -width 0.8000 -pitch_within_group 3.9700 -start_low_ends coordinate  -start_low_ends_coordinate 5.4000 -start_high_ends coordinate  -start_high_ends_coordinate 98.4000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 29.5200 -nets VSS  -layer 29 -width 0.8000 -pitch_within_group 3.9700 -start_low_ends coordinate  -start_low_ends_coordinate 5.4000 -start_high_ends coordinate  -start_high_ends_coordinate 98.4000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 35.6000 -nets VSS  -layer 29 -width 0.8000 -pitch_within_group 3.9700 -start_low_ends coordinate  -start_low_ends_coordinate 5.4000 -start_high_ends coordinate  -start_high_ends_coordinate 98.4000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 38.6400 -nets VSS  -layer 29 -width 0.8000 -pitch_within_group 3.9700 -start_low_ends coordinate  -start_low_ends_coordinate 5.4000 -start_high_ends coordinate  -start_high_ends_coordinate 98.4000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 41.6800 -nets VSS  -layer 29 -width 0.8000 -pitch_within_group 3.9700 -start_low_ends coordinate  -start_low_ends_coordinate 5.4000 -start_high_ends coordinate  -start_high_ends_coordinate 98.4000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 47.7600 -nets VSS  -layer 29 -width 0.8000 -pitch_within_group 3.9700 -start_low_ends coordinate  -start_low_ends_coordinate 5.4000 -start_high_ends coordinate  -start_high_ends_coordinate 98.4000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 50.8000 -nets VSS  -layer 29 -width 0.8000 -pitch_within_group 3.9700 -start_low_ends coordinate  -start_low_ends_coordinate 5.4000 -start_high_ends coordinate  -start_high_ends_coordinate 98.4000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 53.8400 -nets VSS  -layer 29 -width 0.8000 -pitch_within_group 3.9700 -start_low_ends coordinate  -start_low_ends_coordinate 5.4000 -start_high_ends coordinate  -start_high_ends_coordinate 98.4000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 59.9200 -nets VSS  -layer 29 -width 0.8000 -pitch_within_group 3.9700 -start_low_ends coordinate  -start_low_ends_coordinate 5.4000 -start_high_ends coordinate  -start_high_ends_coordinate 98.4000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 62.9600 -nets VSS  -layer 29 -width 0.8000 -pitch_within_group 3.9700 -start_low_ends coordinate  -start_low_ends_coordinate 5.4000 -start_high_ends coordinate  -start_high_ends_coordinate 98.4000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 66.0000 -nets VSS  -layer 29 -width 0.8000 -pitch_within_group 3.9700 -start_low_ends coordinate  -start_low_ends_coordinate 5.4000 -start_high_ends coordinate  -start_high_ends_coordinate 98.4000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 72.0800 -nets VSS  -layer 29 -width 0.8000 -pitch_within_group 3.9700 -start_low_ends coordinate  -start_low_ends_coordinate 5.4000 -start_high_ends coordinate  -start_high_ends_coordinate 98.4000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 75.1200 -nets VSS  -layer 29 -width 0.8000 -pitch_within_group 3.9700 -start_low_ends coordinate  -start_low_ends_coordinate 5.4000 -start_high_ends coordinate  -start_high_ends_coordinate 98.4000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 78.1600 -nets VSS  -layer 29 -width 0.8000 -pitch_within_group 3.9700 -start_low_ends coordinate  -start_low_ends_coordinate 5.4000 -start_high_ends coordinate  -start_high_ends_coordinate 98.4000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 81.2000 -nets VSS  -layer 29 -width 0.8000 -pitch_within_group 3.9700 -start_low_ends coordinate  -start_low_ends_coordinate 5.4000 -start_high_ends coordinate  -start_high_ends_coordinate 98.4000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 87.2800 -nets VSS  -layer 29 -width 0.8000 -pitch_within_group 3.9700 -start_low_ends coordinate  -start_low_ends_coordinate 5.4000 -start_high_ends coordinate  -start_high_ends_coordinate 98.4000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 90.3200 -nets VSS  -layer 29 -width 0.8000 -pitch_within_group 3.9700 -start_low_ends coordinate  -start_low_ends_coordinate 5.4000 -start_high_ends coordinate  -start_high_ends_coordinate 98.4000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
set_pns_commit_mode false
